CareerPortal/Controllers/EducationController.cs
using CareerPortal.DataAccess.Repository.IRepository;
using CareerPortal.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CareerPortal.Controllers
{
    public class EducationController : BaseController
    {
        private readonly IUnitOfWork _unitOfWork;

        public EducationController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            if (!UserInfo.isLoggedIn)
            {
                return RedirectToAction(nameof(Login), "Home");
            }

            IEnumerable<Education> educations = _unitOfWork.Education.GetAll(i => i.UserId == UserInfo.UserID);
            return View(educations);
        }
        public IActionResult Upsert(int? id)
        {
            if (!UserInfo.isLoggedIn)
            {
                return RedirectToAction(nameof(Login), "Home");
            }
            
            Education education;
            if (id == 0 || id == null)
            {
                education = new Education();
                education.UserId = UserInfo.UserID;
                return View(education);
            }

            education = _unitOfWork.Education.Get(id.GetValueOrDefault());
            if (education == null)
            {
                return NotFound();
            }
            return View(education); 
        }




        #region
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Education education)
        {
            if (!UserInfo.isLoggedIn)
            {
                return RedirectToAction(nameof(Login), "Home");
            }
            if (ModelState.IsValid)
            {
                if(education.Id == 0)
                {
                    _unitOfWork.Education.Add(education);
                }
                else
                {
                    _unitOfWork.Education.Update(education);
                }
                _unitOfWork.Save();

                return RedirectToAction(nameof(Index));
            }
            return View(education);
        }


        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var category = _unitOfWork.Education.Get(id);
            if (category == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }
            if (category.UserId != UserInfo.UserID || !UserInfo.isLoggedIn)
            {
                return Json(new { success = false, message = "Unauthenticated delete" });
            }
            _unitOfWork.Education.Remove(category);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Delete successfull" });

        }

        #endregion
    }
}

CareerPortal/Controllers/ExperienceController.cs
using CareerPortal.DataAccess.Repository.IRepository;
using CareerPortal.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CareerPortal.Controllers
{
    public class ExperienceController : BaseController
    {
        private readonly IUnitOfWork _unitOfWork;
        public ExperienceController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            if (!UserInfo.isLoggedIn)
            {
                return RedirectToAction(nameof(Login), "Home");
            }

            IEnumerable<Experience> experiences = _unitOfWork.Experience.GetAll(i => i.UserId == UserInfo.UserID);
            return View(experiences);



        }
        public IActionResult Upsert(int? id)
        {
            if (!UserInfo.isLoggedIn)
            {
                return RedirectToAction(nameof(Login), "Home");
            }
            Experience experience;
            if (id == 0 || id == null)
            {
                experience = new Experience();
                experience.UserId = UserInfo.UserID;
                return View(experience);
            }

            experience = _unitOfWork.Experience.Get(id.GetValueOrDefault());
            if (experience == null)
            {
                return NotFound();
            }
            return View(experience);
        }




        #region
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Experience experience)
        {
            if (!UserInfo.isLoggedIn)
            {
                return RedirectToAction(nameof(Login), "Home");
            }
            if (ModelState.IsValid)
            {
                if (experience.Id == 0)
                {
                    _unitOfWork.Experience.Add(experience);
                }
                else
                {
                    _unitOfWork.Experience.Update(experience);
                }
                _unitOfWork.Save();

                return RedirectToAction(nameof(Index));
            }
            return View(experience);
        }


        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var category = _unitOfWork.Experience.Get(id);
            if (category == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }
            if (category.UserId != UserInfo.UserID || !UserInfo.isLoggedIn)
            {
                return Json(new { success = false, message = "Unauthenticated delete" });
            }
            _unitOfWork.Experience.Remove(category);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Delete successfull" });

        }

        #endregion
    }
}

CareerPortal/Views/Education/Index.cshtml
@model IEnumerable<CareerPortal.Models.Education>
<div class="container">
    <div class="mt-5 row border justify-content-between p-5">
        <div class="col">
            <h3>Education Details</h3>
        </div>
        <div class="col">
            <a asp-action="Upsert" class="btn btn-primary float-right"><i class="fas fa-plus"></i> &nbsp; Add Education</a>
        </div>
        <table class="table mt-4">
            <thead>
                <tr>
                    <th scope="col">Institution</th>
                    <th scope="col">Degree</th>
                    <th scope="col">Score</th>
                    <th scope="col">Enrollment Year</th>
                    <th scope="col">Pass Year</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var education in Model)
                {
                    <tr>
                        <td scope="row">@education.Institution</td>
                        <td>@education.Degree</td>
                        <td>@education.Score</td>
                        <td>@education.EnrollYear</td>
                        <td>@education.PassYear</td>
                        <td>
                            <div class="text-center">
                                <a asp-action="Upsert" asp-route-id="@education.Id" class="btn btn-success text-white" style="cursor:pointer">
                                    <i class="fas fa-edit"></i>
                                </a>
                                <a onclick="Delete('Education/Delete/@education.Id')" class="btn btn-danger text-white" style="cursor:pointer">
                                    <i class="fas fa-trash-alt"></i>
                                </a>
                            </div>
                        </td>
                    </tr>
                }

            </tbody>
        </table>
        <a asp-controller="Experience" asp-action="Index" class="btn btn-primary mt-4 float-right">Next : Add Experience Details</a>
    </div>
</div>


@section Scripts{

    <script src="~/js/delete.js"></script>
    <partial name="_ValidationScriptsPartial" />


}

CareerPortal/Views/Education/Upsert.cshtml
@model CareerPortal.Models.Education
<div class="container">
    <div class="mt-5 row border justify-content-between p-5">
        <div class="col-8 p-5">
            <form method="post">
                <input type="hidden" asp-for="UserId" />
                <div class="row">
                    <div class="col-10">
                        <h3>Add/Edit Education</h3>
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group row mt-4">
                            <div class="col-4">
                                <label asp-for="Institution" class="mt-2">Institution Name</label>
                            </div>
                            <div class="col-8">
                                <input type="text" asp-for="Institution" class="form-control" placeholder="Enter institution name" />
                                <span asp-validation-for="Institution" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-4">
                                <label class="mt-2" asp-for="Degree">Degree</label>
                            </div>
                            <div class="col-8">
                                <input type="text" asp-for="Degree" class="form-control" placeholder="Enter degree name" />
                                <span asp-validation-for="Degree" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-4">
                                <label class="mt-2" asp-for="Score">Score</label>
                            </div>
                            <div class="col-8">
                                <input type="text" asp-for="Score" class="form-control" placeholder="Enter score in percentage" />
                                <span asp-validation-for="Score" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-4">
                                <label class="mt-2" asp-for="EnrollYear">Year of Enrollment</label>
                            </div>
                            <div class="col-8">
                                <input type="text" asp-for="EnrollYear" class="form-control" placeholder="Enter year of enrollment" />
                                <span asp-validation-for="EnrollYear" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-4">
                                <label class="mt-2" asp-for="PassYear">Year of pass</label>
                            </div>
                            <div class="col-8">
                                <input type="text" asp-for="PassYear" class="form-control" placeholder="Enter year of pass" />
                                <span asp-validation-for="PassYear" class="text-danger"></span>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary mt-4">Add / Edit</button>
                    </div>
                </div>
            </form>
        </div>

    </div>
</div>


@section Scripts{
    <partial name="_ValidationScriptsPartial" />
 }